services:
    common-devcontainer:
        image: common-devcontainer
        container_name: common-devcontainer
        build:
            context: ..
            dockerfile: .devcontainer/Dockerfile
        volumes:
            - ..:/workspace:cached
            - ../resources/:/resources
        # This keeps the devcontainer running.
        entrypoint: ["tail", "-f", "/dev/null"]
        networks:
            - common

    common-redis:
        image: redis:8.0.2
        container_name: common-redis
        volumes:
            - $PWD/resources/cache/redis:/data
        networks:
            - common

networks:
    common:
        name: common
        driver: bridge
